# Generated by Django 6.1 on 2026-09-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('especialidade', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('anos_experiencia', models.IntegerField(default=0)),
            ],
        ),
    ]
